# $ docker compose -f docker-compose.yml build
# $ docker compose -f docker-compose.yml up

services:
  app:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - "./work:/home/rstudio"
      - "./lib/R:/usr/local/lib/R/persist-library"
      - "./lib/python:/usr/local/lib/python/persist-library"
    environment:
      - JUPYTER_TOKEN=yourpassword
